apiVersion: v1
kind: Service
metadata:
  name: ai-resume-ats-service
  labels:
    app: ai-resume-ats
spec:
  type: NodePort
  selector:
    app: ai-resume-ats
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
      name: http
